### ISSUE TITLE
Pinball-loss: Unable to fit?

### ISSUE THREAD

**Issue by tpanum** [scikit-learn-contrib/skglm#273]
## Describe the bug

I am unable to fit a simple model using the experimental `Pinball`-loss.

## Steps to reproduce

```
from skglm.experimental import Pinball, PDCD_WS
from skglm import GeneralizedLinearEstimator
from skglm.penalties import L1
from skglm.solvers import ProxNewton

estimator = GeneralizedLinearEstimator(
    datafit=Pinball(.2),
    penalty=L1(alpha=1.),
    solver=ProxNewton(),
)
estimator.fit(X, y)
```

yields

```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'raw_grad' of type instance.jitclass.Pinball#371180a40<quantile_level:float64>

File "../../micromamba/envs/.../lib/python3.12/site-packages/skglm/solvers/prox_newton.py", line 430:
def _construct_grad(X, y, w, Xw, datafit, ws):
    <source elided>
    # recomputing raw_grad for every j, which is costly for logreg
    raw_grad = datafit.raw_grad(y, Xw)
    ^
    ```

**Comment by mathurinm** [comment]
@tpanum thanks for the feedback.
First, may I ask in which situation you're using skglm, and what are its benefits for you?


Second, a recent PR was merged into `main` that should give a more informative feedback:
```
AttributeError: Pinball is not compatible with solver ProxNewton. It must implement `raw_grad` and `raw_hessian`.
Missing `raw_grad` and `raw_hessian`.
```
This is because the pinball is not differentiable (we could implement its gradient almost everywhere nevertheless, but the real issue is that Hessian is equal to 0 almost everywhere, so right now I don't see how one can use ProxNewton.

I'm opening #274 with some fixes that will allow you to use PDCD_WS solver, while we check if other faster solvers could be made compatible too.

**Comment by tpanum** [comment]
@mathurinm Thanks a ton for the kind response.

I do quantitative finance, and I find scikit-learn's regular `QuantileRegressor` painfully slow, and have enjoyed using `skglm` for other tasks in the past.

Having just some compatible solver would be fantastic, thanks a lot for looking into it so rapidly.

**Comment by mathurinm** [comment]
@tpanum please pull from main, you should now be able to use the only solver that is comaptible with a non smooth datafit + a nonsmooth penalty: `PDCD_WS`

I believe we could try to come up with a custom approach to be faster, but it would require some work. If you are not satisfied with the performance of PDCD_WS and want to give it a try, let us know!

I'm closing for now, reopen if need be.
