### ISSUE TITLE
ENH AndersonAccelerator.accelerate() does not create new points most of the time

### ISSUE THREAD

**Issue by mathurinm** [scikit-learn-contrib/skglm#40]
This means computation of `p_obj_acc` is not needed. It's a big bottleneck in datasets such as Finance where the subproblems are very small compared to `n_features`.

Returning an additional boolean variable as the output of `accelerate` would allow us to skip the `p_obj_acc` computation in cases where it's not needed

**Comment by QB3** [comment]
I guess this is linked to #33

**Comment by mathurinm** [comment]
That's where I noticed it, but it should be fixed in main first, before the other PR is merged, to make reviewing and benchmarking easier 

@Badr-MOUFAD will have a look in the upcoming days

**Comment by QB3** [comment]
OK but just to be sure, this problem only appears in the group solver? https://github.com/scikit-learn-contrib/skglm/blob/1f13430fe208e33f423a41b23e4aa3df64a62d1d/skglm/solvers/group_bcd_solver.py#L94

For me it does not appear:
- in the single task solver, if the error is raised, then `p_obj_acc` is not computed https://github.com/scikit-learn-contrib/skglm/blob/1f13430fe208e33f423a41b23e4aa3df64a62d1d/skglm/solvers/cd_solver.py#L301
- in the multitask solver https://github.com/scikit-learn-contrib/skglm/blob/1f13430fe208e33f423a41b23e4aa3df64a62d1d/skglm/solvers/multitask_bcd_solver.py#L266

**Comment by Badr-MOUFAD** [comment]
``AndersonAcceleration.extrapolate(w, Xw)`` returns the same (w, Xw) for iteration between 0 and K-1 (to construct the matrix of residuals) and return (w_acc, Xw_acc) at the K iteration.

Hence, we don't need to evaluate ``p_obj_acc`` (L96) for iteration 0 till K-1 since it is the same as ``p_obj``.

https://github.com/scikit-learn-contrib/skglm/blob/f5e81543cf76a02471deb2e3a3a82ecad83c2ccf/skglm/solvers/group_bcd_solver.py#L94-L100

> OK but just to be sure, this problem only appears in the group solver?

Indeed @QB3, so far this problem is only related to the group solver as it is the only one using ``AndersonAccelaration``.
However, AA class will be adopted in other solvers (#33). Hence the need to handle this problem.

----------------
thx @mathurinm, that's a nice catch!
